name: todos_core_repository
description: An app-agnostic data source that can be used by all implementations

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  meta:
  freezed_annotation: ^0.14.3
  json_serializable: ^5.0.2

dev_dependencies:
  build_runner: ^2.1.2
  freezed: ^0.14.5